default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: planigle_development
  username: root
  password: 

test:
  <<: *default
  database: planigle_test
  username: root
  password:

production:
  <<: *default
  database: planigle_production
  username: root
  password: 
